package com.luizin.lembreteagua;
import android.Manifest;import android.app.*;import android.content.*;import android.content.pm.PackageManager;import android.graphics.Color;import android.net.Uri;import android.os.*;import android.provider.Settings;import android.widget.*;
public class MainActivity extends Activity{
 TextView status; Button activate; boolean active;
 public void onCreate(Bundle b){super.onCreate(b);setContentView(R.layout.activity_main);status=findViewById(R.id.status);activate=findViewById(R.id.btnActivate);Button disable=findViewById(R.id.btnDisable);TextView settings=findViewById(R.id.settingsLink);createChannel();activate.setOnClickListener(v->{requestNotifications();requestExact();ReminderScheduler.scheduleAll(this);active=true;update();});disable.setOnClickListener(v->{ReminderScheduler.cancelAll(this);active=false;update();});settings.setOnClickListener(v->requestExact());}
 void update(){if(active){status.setText("Lembretes ativos • 10:30 até 20:30");status.setTextColor(Color.rgb(20,104,170));activate.setText("✓ LEMBRETES ATIVOS");}else{status.setText("Seis lembretes por dia, a cada 2 horas");status.setTextColor(Color.rgb(109,140,166));activate.setText("ATIVAR LEMBRETES");}}
 void requestNotifications(){if(Build.VERSION.SDK_INT>=33&&checkSelfPermission(Manifest.permission.POST_NOTIFICATIONS)!=PackageManager.PERMISSION_GRANTED)requestPermissions(new String[]{Manifest.permission.POST_NOTIFICATIONS},20);}
 void requestExact(){if(Build.VERSION.SDK_INT>=31){AlarmManager a=(AlarmManager)getSystemService(ALARM_SERVICE);if(!a.canScheduleExactAlarms())try{startActivity(new Intent(Settings.ACTION_REQUEST_SCHEDULE_EXACT_ALARM, Uri.parse("package:"+getPackageName())));}catch(Exception ignored){}}}
 void createChannel(){if(Build.VERSION.SDK_INT>=26){NotificationChannel c=new NotificationChannel(AlarmReceiver.CHANNEL_ID,"Lembretes de água",NotificationManager.IMPORTANCE_HIGH);c.setDescription("Lembretes de hidratação");c.enableVibration(true);((NotificationManager)getSystemService(NOTIFICATION_SERVICE)).createNotificationChannel(c);}}
}
