package com.luizin.lembreteagua;
import android.app.*; import android.content.*; import android.os.Build; import java.util.Calendar; import java.util.Locale;
public final class ReminderScheduler { private static final int[] HOURS={10,12,14,16,18,20}; private ReminderScheduler(){}
 public static void scheduleAll(Context c){AlarmManager am=(AlarmManager)c.getSystemService(Context.ALARM_SERVICE); if(am==null)return; for(int h:HOURS){scheduleHour(c,am,h,false);}}
 public static void scheduleNextDayForRequestCode(Context c,int requestCode){AlarmManager am=(AlarmManager)c.getSystemService(Context.ALARM_SERVICE);if(am==null)return;int hour=requestCode/100;for(int h:HOURS){if(h==hour){scheduleHour(c,am,h,true);break;}}}
 private static void scheduleHour(Context c,AlarmManager am,int h,boolean forceTomorrow){Calendar x=Calendar.getInstance();x.set(Calendar.HOUR_OF_DAY,h);x.set(Calendar.MINUTE,30);x.set(Calendar.SECOND,0);x.set(Calendar.MILLISECOND,0);if(forceTomorrow||x.getTimeInMillis()<=System.currentTimeMillis())x.add(Calendar.DAY_OF_YEAR,1);int rc=h*100+30;Intent i=new Intent(c,AlarmReceiver.class);i.putExtra("requestCode",rc);PendingIntent pi=PendingIntent.getBroadcast(c,rc,i,PendingIntent.FLAG_UPDATE_CURRENT|PendingIntent.FLAG_IMMUTABLE);if(Build.VERSION.SDK_INT>=31&&canScheduleExactAlarms(c))am.setExactAndAllowWhileIdle(AlarmManager.RTC_WAKEUP,x.getTimeInMillis(),pi);else am.setAndAllowWhileIdle(AlarmManager.RTC_WAKEUP,x.getTimeInMillis(),pi);}
 public static void cancelAll(Context c){AlarmManager am=(AlarmManager)c.getSystemService(Context.ALARM_SERVICE);if(am==null)return;for(int h:HOURS){int rc=h*100+30;Intent i=new Intent(c,AlarmReceiver.class);PendingIntent pi=PendingIntent.getBroadcast(c,rc,i,PendingIntent.FLAG_UPDATE_CURRENT|PendingIntent.FLAG_IMMUTABLE);am.cancel(pi);pi.cancel();}}
 public static boolean canScheduleExactAlarms(Context c){if(Build.VERSION.SDK_INT<31)return true;AlarmManager am=(AlarmManager)c.getSystemService(Context.ALARM_SERVICE);return am!=null&&am.canScheduleExactAlarms();}
 public static int reminderCount(){return HOURS.length;}
 public static String scheduleWindowLabel(){return String.format(Locale.getDefault(),"%02d:30 até %02d:30",HOURS[0],HOURS[HOURS.length-1]);}
}
